services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./web/images:/usr/share/nginx/html/images:ro
      - ./web/conf:/etc/nginx/conf.d:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    networks:
      - nginx_network

  web-proxy:
    build:
      context: ./web-proxy
    container_name: web-proxy
    volumes:
      - ./web-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-proxy/conf:/etc/nginx/conf.d:ro
    ports:
      - "8080:80"
    networks:
      - nginx_network
    depends_on:
      - web

  test:
    build:
      context: ./tests
    volumes:
      - ./tests/scripts:/scripts
    networks:
      - nginx_network

networks:
  nginx_network: